config/routes.rb
Rails.application.routes.draw do
  root 'kittens#index'
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, 	   presence: true
  validates :age, 	   presence: true
  validates :cuteness, presence: true
  validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = 'You created a kitten! :)'
    else
      flash[:danger] = 'No kitten has been made! :('
      render 'new'
    end
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update_attributes(kitten_params)
      flash[:success] = 'Kitten has been updated! ^_^'
      redirect_to @kitten 
    else
      flash[:danger] = 'Kitten has not been updated! -_-'
      render 'edit'
    end 
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    flash[:success] = 'No more kitten'
    redirect_to root_path
  end

  private

    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for @kitten do |f| %>
  <%= f.label :name, class: "control-label" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :age, class: "control-label" %>
  <%= f.text_field :age, class: "form-control" %>

  <%= f.label :cuteness, class: "control-label" %>
  <%= f.text_field :cuteness, class: 'form-control' %>

  <%= f.label :softness, class: "control-label" %>
  <%= f.text_field :softness, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/kittens/edit.html.erb
<% provide(:button_text, 'Update Kitten')

<h1>Edit your Kitten</h1>

<%= render 'form' %>

<%= link_to 'destroy', kittens_path, method: :delete, class: "btn btn-danger" %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>

<table>
  <thead>
    <tr>
      <th>Name:</th>
      <th>Age:</th>
      <th>Cuteness:</th>
      <th>Softness:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kittens.each do |kitten| %>
      <tr>
        <td><%= kitten.name %></td>
        <td><%= kitten.age %></td>
        <td><%= kitten.cuteness %></td>
        <td><%= kitten.softness %></td>
        <td><%= link_to 'destroy', kitten_path(kitten), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/kittens/new.html.erb
<% provide(:button_text, "Create Kitten")

<h1>Make a New Kitten</h1>

<%= render 'form' %>

app/views/kittens/show.html.erb
<h1>Kittens ^_^</h1>

<p>
  <strong>Name:</strong>
  <%= @kitten.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @kitten.age %>
</p>

<p>
  <strong>Cuteness:</strong>
  <%= @kitten.cuteness %>
</p>

<p>
  <strong>Softness:</strong>
  <%= @kitten.softness %>
</p>

<%= link_to 'destroy', kitten_path, method: :delete, class: "btn btn-danger" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>